version: 2
jobs:
build:
  docker:
    - image: circleci/openjdk:8-jdk-browser
    steps:
      - checkout
      - restore_cache:
          key: todo-{{ checksum: pom.xml}}
      - run: mvn dependency:go-offline
      - save_cache:
          key: todo-{{ checksum: pom.xml}}
      - run: mvn clean install
deploy:
  docker:
  - image:  circleci/openjdk:8-jdk-browser
  steps:
  - checkout

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
