apiVersion: v1
kind: Service
metadata:
  name: todo-service-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
